# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "9da8c11d2cd88979e1decd67aade27fe"
name = "Subscription Managments App"
handle = "subscription-managments-app"
application_url = "https://fingers-assisted-mistakes-conservation.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "cm-menu.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,read_products,write_orders,write_products"

[auth]
redirect_urls = [
  "https://fingers-assisted-mistakes-conservation.trycloudflare.com/auth/callback",
  "https://fingers-assisted-mistakes-conservation.trycloudflare.com/auth/shopify/callback",
  "https://fingers-assisted-mistakes-conservation.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

[pos]
embedded = false
